mixed-port: 7890
external-controller: 127.0.0.1:9090
mode: rule
log-level: error
proxies:
proxy-groups:
  - name: "PROXY"
    type: select
    use:
      - nodes
proxy-providers:
  nodes:
    type: file
    path: ./list.yml
    interval: 0
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 0
rules:
  - MATCH,PROXY
